# Generated by Django 5.1.3 on 2024-11-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_messageschedule_is_reminder_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.PositiveIntegerField(default=99),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='problem',
            field=models.TextField(default=1, verbose_name="Patient's Problem"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='treatment',
            field=models.ManyToManyField(to='crm.treatment'),
        ),
    ]
